### ISSUE TITLE
Error retrieving metadata.

### ISSUE THREAD

**Issue by XilinJia** [vvigilante/youtube-subtitles-downlaoder#3]
Nice package.

$ ytsubtitles https://www.youtube.com/watch?v=luwBu6e1ULg --lang=en
Error retrieving metadata. The video may be non-existing or be licensed.

So, what does this mean?

**Comment by vvigilante** [comment]
Hi, thank you for your message.

The current implementation requires that only the video ID is passed as first parameter.

Your command should therefore look like this
```bash
ytsubtitles luwBu6e1ULg --lang=en
```

Alternatively, please update to latest version 0.1.0, which supports your syntax
